name: Deploy Preview

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        workspace: [meechain-dapp, hexchain-dapp, token-dashboard] # เพิ่ม workspace ตามต้องการ

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build workspace
        run: npm run build --workspace=${{ matrix.workspace }}

      - name: Configure Pages
        uses: actions/configure-pages@v3

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./packages/${{ matrix.workspace }}/dist
          retention-days: 1

      - name: Validate config
        run: node scripts/validate-config.js ${{ matrix.workspace }}

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
        with:
         strategy:
  matrix:
    include:
      - workspace: strategy:
  matrix:
    include:
      - workspace: hexchain-dapp
        network: mainnet
      - workspace: meechain-dapp
        network: mainnet
      - workspace: token-dashboar    # React/Vite หรือ Webpack
        network: mainnet

          subdomain: ${{ matrix.workspace }}, ${{ matrix.network }}
